name: datasets

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create data directory
        run: mkdir -p $GITHUB_WORKSPACE/data

      - name: Run your script
        run: |
          python train_model_pii.py

        env:
          GITHUB_WORKSPACE: ${{github.workspace }}
