name: datasets

on:
  push:
    branches:
        - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create data directory
        run: mkdir -p $GITHUB_WORKSPACE/data

      - name: Run your script
        run: |
          python train_model_pii.py


      - name: Install Dependices
        run: |
         
          pip install torch
          pip install transformers
          pip install datasets
          pip install seqeval
          pip install git+https://github.com/huggingface/transformers.git
          pip install wandb
          pip install evaluate

        env:
          GITHUB_WORKSPACE: ${{github.workspace }}
