name: Train Model

on:
  push:
    branches:
      - main

jobs:
  train:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install Dependencies
      run: |
        pip install torch
        pip install transformers
        pip install datasets
        pip install seqeval
        pip install git+https://github.com/huggingface/transformers.git
        pip install wandb
      
        pip intall evaluate

    - name: Train Model
      run: python train_model_pii.py  # replace with your actual script name
      env:
        WANDB_API_KEY: ${{ secrets.WANDB_API_KEY }}
